In [1]:
#Numpy
#Adding
# If we add a scalar value to the array, numpy will add that value to each element

import numpy as mult
vector1=mult.array([134, 234, 203, 571, 40, -37])
vector2=mult.array([4, 5, 25, 51, 5, 33])

z=vector1+5
print(z)

z=vector2-100
print(z)

vector2[2:4]=vector2[2:4]-100
print(vector2)


[139 239 208 576  45 -32]
[-96 -95 -75 -49 -95 -67]
[  4   5 -75 -49   5  33]
