In [4]:
#Numpy
#Basic Operations

#Numpy makes it easier to do many operations that are commonly performed in data science
#These same operations are usually computationally faster and require less memory in numpy compared

#list
#list
#list
#list
#list
#list

#Vector addition
#Vector addition is a widely used operation in data science

V1=[1, 2, 4.5, 6.7, 9, 1.6, 7]
V2=[4, 7, 11, 67, 7, 7.8, 6]
print('Vector 1:\n', V1)
print('\nVector 2:\n', V2)
#The following 3 lines of code will add the two lists and place the result in the list 'z'
AddResult=[]
for n,m in zip(V1, V2):
    AddResult.append(n+m)
    
print('\n Result vector 1 + vector 2= Vector:')
print(AddResult)

V1=[1, 2, 20, 71, 0, -7]
V2=[4, 5, 25, 51, 5, 33]
V3=[11, 25, 5, 1, 5, 23] 

print('Vector 1:\n', V1)
print('\nVector 2:\n', V2)
print('\nVector 3:\n', V3)

z1=[]
for n,m in zip(V1, V2):
    z1.append(n+m)
z2=[]
for n,m in zip(V1, V2):
    z2.append(n+m)

print('\n Result vector 1 + vector 2= ZVector1:')
print(z1)
print('\n Result vector 1 + vector 2= ZVector2:')
print(z2)

#Array
#Array
#Array
#Array
#Array
#Array

#We can also perform vector addition with one line of numpy code
import numpy as vect
vector1=vect.array([1, 2, 20, 71, 0, -7])
vector2=vect.array([4, 5, 25, 51, 5, 33])
print('\n Result vector 1 + vector 2= Vector:')
z=vector1+vector2
print(z)

#Subtraction 
#We can also perform vector subtraction by changing the addition sign to a subtraction sign
print('Subtraction')
import numpy as e212
vector1=e212.array([1, 2, 20, 71, 0, -7])
vector2=e212.array([4, 5, 25, 51, 5, 33])
print('Vector 1 - Array:\n', vector1)
print('\nVector 2 - Array:\n', vector2)
#The following 3 lines of code will add the two lists and place the result in the list 'z'
z=[]
for n,m in zip(vector1, vector2):
    z.append(n-m)
print('\n Result vector 1 - vector 2= Vector:')
print(z)

vector1=vect.array([1, 2, 20, 71, 0, -7])
vector2=vect.array([4, 5, 25, 51, 5, 33])
print('\n Result vector 1 - vector 2= Vector:')
z=vector1-vector2
print(z)


Vector 1:
 [1, 2, 4.5, 6.7, 9, 1.6, 7]

Vector 2:
 [4, 7, 11, 67, 7, 7.8, 6]

 Result vector 1 + vector 2= Vector:
[5, 9, 15.5, 73.7, 16, 9.4, 13]
Vector 1:
 [1, 2, 20, 71, 0, -7]

Vector 2:
 [4, 5, 25, 51, 5, 33]

Vector 3:
 [11, 25, 5, 1, 5, 23]

 Result vector 1 + vector 2= ZVector1:
[5, 7, 45, 122, 5, 26]

 Result vector 1 + vector 2= ZVector2:
[5, 7, 45, 122, 5, 26]

 Result vector 1 + vector 2= Vector:
[  5   7  45 122   5  26]
Subtraction
Vector 1 - Array:
 [ 1  2 20 71  0 -7]

Vector 2 - Array:
 [ 4  5 25 51  5 33]

 Result vector 1 - vector 2= Vector:
[-3, -3, -5, 20, -5, -40]

 Result vector 1 - vector 2= Vector:
[ -3  -3  -5  20  -5 -40]


In [7]:
V1=[1, 2, 20, 71, 0, -7]
V2=[4, 5, 25, 51, 5, 33]
V3=[11, 25, 5, 1, 5, 23] 
V4=[2.5, 5.6, 7, 8, 8.4, 6]
print('Vector 1:\n', V1)
print('\nVector 2:\n', V2)
print('\nVector 3:\n', V3)

import numpy as s1
V1=s1.array(V1)
V2=s1.array(V2)
V3=s1.array(V3)

z=[]
for n,m,i,j in zip(V1, V2, V3, V4):
    z.append(n+m+i+j)
print('\n Result vector 1 + vector 2+ vector 3 + vector 4 :')
print(z)

Vector 1:
 [1, 2, 20, 71, 0, -7]

Vector 2:
 [4, 5, 25, 51, 5, 33]

Vector 3:
 [11, 25, 5, 1, 5, 23]

 Result vector 1 + vector 2+ vector 3 + vector 4 :
[18.5, 37.6, 57, 131, 18.4, 55]


In [8]:
V1=[1, 2, 20, 71, 0, -7]
V2=[4, 5, 25, 51, 5, 33]
V3=[11, 25, 5, 1, 5, 23] 
V4=[2.5, 5.6, 7, 8, 8.4, 6]
print('Vector 1:\n', V1)
print('\nVector 2:\n', V2)
print('\nVector 3:\n', V3)

import numpy as s1
V1=s1.array(V1)
V2=s1.array(V2)
V3=s1.array(V3)

z=[]
for n,m,i,j in zip(V1, V2, V3, V4):
    z.append(n-m-i-j)
print('\n Result vector 1 - vector 2 - vector 3 - vector 4 :')
print(z)

Vector 1:
 [1, 2, 20, 71, 0, -7]

Vector 2:
 [4, 5, 25, 51, 5, 33]

Vector 3:
 [11, 25, 5, 1, 5, 23]

 Result vector 1 - vector 2 - vector 3 - vector 4 :
[-16.5, -33.6, -17, 11, -18.4, -69]


In [9]:
V1=[1, 2, 20, 71, 0, -7]
V2=[4, 5, 25, 51, 5, 33]
V3=[11, 25, 5, 1, 5, 23] 
V4=[2.5, 5.6, 7, 8, 8.4, 6]
print('Vector 1:\n', V1)
print('\nVector 2:\n', V2)
print('\nVector 3:\n', V3)

import numpy as s1
V1=s1.array(V1)
V2=s1.array(V2)
V3=s1.array(V3)

z=[]
for n,m,i,j in zip(V1, V2, V3, V4):
    z.append(n+m-i+j)
print('\n Result vector 1 + vector 2 - vector 3 + vector 4 :')
print(z)

Vector 1:
 [1, 2, 20, 71, 0, -7]

Vector 2:
 [4, 5, 25, 51, 5, 33]

Vector 3:
 [11, 25, 5, 1, 5, 23]

 Result vector 1 + vector 2 - vector 3 + vector 4 :
[-3.5, -12.4, 47, 129, 8.4, 9]
