In [1]:
#Numpy
#Vector multiplication
#Vector multiplication with a Scalar is another commonly performed operation
import numpy as mult

vector1=mult.array([134, 234, 203, 571, 40, -37])
vector2=mult.array([4, 5, 25, 51, 5, 33])
vector3=mult.array([2, 35, 5, 7,55, 83])

print('\nVector multiplication Ex1:')
z=2*vector1
print(z)

print('\nVector multiplication Ex2:')
z=9*vector3
print(z)


print('\nVector multiplication Ex3:')
z=3*vector2
print(z)

#Another Method for multiplication
z=[]
print('\nAnother Method for multiplication Ex 1:')
for n in vector1:
    z.append(2*n)
print(z)

print('\nAnother Method for multiplication Ex 2:')
for n in vector2:
    z.append(4*n)
print(z)

print('\nAnother Method for multiplication Ex 3:')
for n in vector3:
    z.append(8*n)
print(z)



Vector multiplication Ex1:
[ 268  468  406 1142   80  -74]

Vector multiplication Ex2:
[ 18 315  45  63 495 747]

Vector multiplication Ex3:
[ 12  15  75 153  15  99]

Another Method for multiplication Ex 1:
[268, 468, 406, 1142, 80, -74]

Another Method for multiplication Ex 2:
[268, 468, 406, 1142, 80, -74, 16, 20, 100, 204, 20, 132]

Another Method for multiplication Ex 3:
[268, 468, 406, 1142, 80, -74, 16, 20, 100, 204, 20, 132, 16, 280, 40, 56, 440, 664]
